version: "3"
services:

  nginx:
    links:
      - auth-jwt
    volumes:
      - ./apps/nginx/dist/:/usr/share/nginx/html

  auth-jwt:
    container_name: auth-jwt

  auth-sam:
    container_name: auth-sam
