version: "3"
services:
  nginx:
    container_name: nginx-DEV
    build: 
      context: ./apps/nginx
      dockerfile: dev.Dockerfile
    ports:
      - 4200:80
  nodejs-auth:
    container_name: nodejs-auth-DEV
    volumes:
      - ./apps/nodejs-auth/src:/app/src
      - nodejs-auth_node_modules:/app/node_modules
    build:
      context: ./apps/nodejs-auth/
      dockerfile: dev.Dockerfile
  

volumes:
  nodejs-auth_node_modules: