version: "3"
services:
  nginx:
    container_name: nginx-DEV
    build: 
      context: ./apps/nginx
      dockerfile: dev.Dockerfile
    ports:
      - 4200:80
  auth-jwt:
    container_name: auth-jwt-DEV
    volumes:
      - ./apps/auth-jwt/src:/app/src
      - auth-jwt_node_modules:/app/node_modules
    build:
      context: ./apps/auth-jwt/
      dockerfile: dev.Dockerfile
  auth-sam:
    container_name: auth-sam-DEV
    volumes:
      - ./apps/auth-sam:/app
      - auth-sam_node_modules:/app/node_modules
    build:
      context: ./apps/auth-sam/
      dockerfile: dev.Dockerfile

volumes:
  auth-jwt_node_modules:
  auth-sam_node_modules: