version: "3"
services:
  auth-example-nginx:
    container_name: auth-example-nginx-DEV
    build: 
      context: ./apps/nginx
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
  auth-example-auth-jwt:
    container_name: auth-example-auth-jwt-DEV
    volumes:
      - ./apps/auth-jwt/src:/app/src
      - auth-example-auth-jwt_node_modules:/app/node_modules
    build:
      context: ./apps/auth-jwt/
      dockerfile: dev.Dockerfile
  auth-example-auth-sam:
    container_name: auth-example-auth-sam-DEV
    volumes:
      - ./apps/auth-sam:/app
      - auth-example-auth-sam_node_modules:/app/node_modules
    build:
      context: ./apps/auth-sam/
      dockerfile: dev.Dockerfile
  auth-example-api-sample:
    container_name: auth-example-api-sample-DEV
    volumes:
      - ./apps/api-sample:/app
      - auth-example-api-sample_node_modules:/app/node_modules
    build:
      context: ./apps/api-sample/
      dockerfile: dev.Dockerfile

volumes:
  auth-example-auth-jwt_node_modules:
  auth-example-auth-sam_node_modules:
  auth-example-api-sample_node_modules: